# Generated by Django 3.1.4 on 2020-12-05 19:54

from django.db import migrations
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
            ],
            options={
                'verbose_name': 'staff member',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', staff.models.StaffManager()),
            ],
        ),
    ]
