# Generated by Django 3.1.4 on 2020-12-05 20:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('notes', models.TextField(blank=True, help_text='These are never shown to students.', verbose_name='Staff notes')),
                ('status', model_utils.fields.StatusField(choices=[('private', 'Private'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='private', help_text='Hidden from students when private (visible, but not listed, when retired).', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor='status')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.SlugField(max_length=25, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('dri', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='These are never shown to students.', verbose_name='Staff notes')),
                ('status', model_utils.fields.StatusField(choices=[('private', 'Private'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='private', help_text='Hidden from students when private (visible, but not listed, when retired).', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor='status')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='problems.problem')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='problems',
            field=models.ManyToManyField(through='quizzes.QuizProblem', to='problems.Problem'),
        ),
    ]
