# Generated by Django 3.1.4 on 2020-12-05 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20201205_2052'),
        ('students', '0001_initial'),
        ('quizzes', '0002_auto_20201205_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizproblem',
            unique_together={('quiz', 'problem')},
        ),
        migrations.CreateModel(
            name='QuizStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='These are never shown to students.', verbose_name='Staff notes')),
                ('status', model_utils.fields.StatusField(choices=[('private', 'Private'), ('published', 'Published'), ('retired', 'Retired')], db_index=True, default='private', help_text='Hidden from students when private (visible, but not listed, when retired).', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, editable=False, monitor='status')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('timeframed', django.db.models.manager.Manager()),
            ],
        ),
    ]
