# Generated by Django 3.1.4 on 2020-12-05 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('problems', '0002_auto_20201205_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='These are never shown to students.', verbose_name='Staff notes')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('correct', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='StudentProblemSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.TextField()),
                ('comment', models.TextField(help_text='Comments from student about submission.')),
                ('results', models.JSONField(default='{}', help_text='JSON of results of test cases.')),
                ('studentproblem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.studentproblem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
